### PR TITLE
v0.5 smap value tests

### PR DESCRIPTION
**Pull request by SoftwareLiteracy**
smap tests against cppEDM/pyEDM for returned values. 

The original `test_smap()` function that compared rho values should probably be updated once the values match. 

Thanks!

### CODE REVIEW

**Comment by keichi** [comment]
Thanks for this. Can you change the permission of this pull request so I can add commits?

**Comment by keichi** [comment]
Turns out PRs from organization repositories cant't be edited:
https://github.com/orgs/community/discussions/9921

No problem, I will merge this PR and open another PR with the fixes.

**Comment by SoftwareLiteracy** [comment]
PR's from organizations can't be merged _by the owner of the repository_ ?  The logic escapes me. 

Good to know, sorry for the misstep. I'll try to be more careful in the future.

**Comment by keichi** [comment]
I can merge PRs from org accounts, I just can't edit (add/remove commits) them.

**Comment by keichi** [comment]
@SoftwareLiteracy FYI this has been fixed in #36. There is still some small deviation from pyEDM, but it seems it's caused by the difference in precision (double vs float).

Here is a plot comparing pyEDM vs kEDM S-map predictions:
Screen Shot 2023-05-27 at 14 59 48

Excel file comparing S-map coefficients
[smap_valid_blk3sp_x_1_100_smap_coefs.xlsx](https://github.com/keichi/kEDM/files/11581107/smap_valid_blk3sp_x_1_100_smap_coefs.xlsx)

Excel file comparing S-map predictions
[smap_valid_blk3sp_x_1_100.xlsx](https://github.com/keichi/kEDM/files/11581104/smap_valid_blk3sp_x_1_100.xlsx)

**Comment by SoftwareLiteracy** [comment]
@keichi: Thanks for the check. 

Perhaps I do not have the correct version as my test still show a discrepancy.  Here is a test app (renamed with .txt to attach) and results from my machine. 

[kedm-info-Morpheus.txt](https://github.com/keichi/kEDM/files/11584567/kedm-info-Morpheus.txt)
[smap_block3sp_E3.csv](https://github.com/keichi/kEDM/files/11584568/smap_block3sp_E3.csv)
[kedm-smap.py.txt](https://github.com/keichi/kEDM/files/11584570/kedm-smap.py.txt)
[block_3sp.csv](https://github.com/keichi/kEDM/files/11584583/block_3sp.csv)

**Comment by keichi** [comment]
Apologies, I thought I released the version with the fixes. Now it's available on PyPi as 0.6.0.

Also please change:
```
    target_   = df[ target  ].iloc[ libRange  ].values
```
to
```
    target_   = df[ target  ].iloc[ predRange  ].values
```

**Comment by SoftwareLiteracy** [comment]
@keichi : Thank you. 

I installed and tested kedm 0.6.0+2.g72df966 on ika, and 0.6.0 on Morpheus.  Both installations pass all simplex and smap tests in relation to cppEDM/pyEDM.  Excellent!

**Pull request merged**
